rm(list = ls())
source("functions.R")
library(tidyverse)

exclude <- c("SCHEDULED_FORM_NAME", "UPLOADED_BY", "MODIFIED_DT", "FORM_STATUS")
keys <- c("PATIENT_DISPLAY_ID", "FACILITY_DISPLAY_ID")
# demographics <- preprocess("xlsx/Demographics.xlsx", 0, keys, exclude, 1)
# write.table(demographics,"csv/demographics.csv",sep="\t",col.names=TRUE, row.names=FALSE)
diagnosis <- preprocess("xlsx/Diagnosis.xlsx", 14, keys, exclude, 1)
diagnosis$Genetic.mutation.frame.type[is.na(diagnosis$Genetic.mutation.frame.type)] <- "Unknown"
write.table(diagnosis,"csv/diagnosis.csv",sep="\t",col.names=TRUE, row.names=FALSE)
# discontinued <- preprocess("xlsx/Discontinued.xlsx", 0, keys, exclude, 1)
# write.table(discontinued,"csv/discontinued.csv",sep="\t",col.names=TRUE, row.names=FALSE)
encounters <- preprocess("xlsx/Encounter.xlsx", 14, c("PATIENT_DISPLAY_ID", "FACILITY_DISPLAY_ID", "CASE_ID"), exclude, 1)
encounters$individual <- paste(encounters$PATIENT_DISPLAY_ID, encounters$FACILITY_DISPLAY_ID)
# write.table(encounters, "csv/encounters/encounter.csv", sep="\t", col.names=TRUE, row.names=FALSE)
#
# hospitalization <- preprocess("xlsx/Encounter.xlsx", 0, c("PATIENT_DISPLAY_ID", "FACILITY_DISPLAY_ID", "CASE_ID"), exclude, 3)
# hospitalization$individual <- paste(hospitalization$PATIENT_DISPLAY_ID, hospitalization$FACILITY_DISPLAY_ID)
# write.table(hospitalization, "csv/encounters/hospitalization.csv", sep="\t", col.names=TRUE, row.names=FALSE)
# pulmonary_device <- preprocess("xlsx/Encounter.xlsx", 0, c("PATIENT_DISPLAY_ID", "FACILITY_DISPLAY_ID", "CASE_ID"), exclude, 4)
# pulmonary_device$individual <- paste(pulmonary_device$PATIENT_DISPLAY_ID, pulmonary_device$FACILITY_DISPLAY_ID)
# write.table(pulmonary_device, "csv/encounters/pulmonary_device.csv", sep="\t", col.names=TRUE, row.names=FALSE)
# icd <- preprocess("xlsx/Encounter.xlsx", 0, c("PATIENT_DISPLAY_ID", "FACILITY_DISPLAY_ID", "CASE_ID"), exclude, 5)
# icd$individual <- paste(icd$PATIENT_DISPLAY_ID, icd$FACILITY_DISPLAY_ID)
# write.table(icd, "csv/encounters/icd.csv", sep="\t", col.names=TRUE, row.names=FALSE)
# surgery <- preprocess("xlsx/Encounter.xlsx", 0, c("PATIENT_DISPLAY_ID", "FACILITY_DISPLAY_ID", "CASE_ID"), exclude, 6)
# surgery$individual <- paste(surgery$PATIENT_DISPLAY_ID, surgery$FACILITY_DISPLAY_ID)
# write.table(surgery, "csv/encounters/surgery.csv", sep="\t", col.names=TRUE, row.names=FALSE)
# assistive_device <- preprocess("xlsx/Encounter.xlsx", 0, c("PATIENT_DISPLAY_ID", "FACILITY_DISPLAY_ID", "CASE_ID"), exclude, 7)
# assistive_device$individual <- paste(assistive_device$PATIENT_DISPLAY_ID, assistive_device$FACILITY_DISPLAY_ID)
# write.table(assistive_device, "csv/encounters/assistive_device.csv", sep="\t", col.names=TRUE, row.names=FALSE)
# tendon_release <- preprocess("xlsx/Encounter.xlsx", 0, c("PATIENT_DISPLAY_ID", "FACILITY_DISPLAY_ID", "CASE_ID"), exclude, 8)
# tendon_release$individual <- paste(tendon_release$PATIENT_DISPLAY_ID, tendon_release$FACILITY_DISPLAY_ID)
# write.table(tendon_release, "csv/encounters/tendon_release.csv", sep="\t", col.names=TRUE, row.names=FALSE)
# feeding_tube <- preprocess("xlsx/Encounter.xlsx", 0, c("PATIENT_DISPLAY_ID", "FACILITY_DISPLAY_ID", "CASE_ID"), exclude, 9)
# feeding_tube$individual <- paste(feeding_tube$PATIENT_DISPLAY_ID, feeding_tube$FACILITY_DISPLAY_ID)
# write.table(feeding_tube, "csv/encounters/feeding_tube.csv", sep="\t", col.names=TRUE, row.names=FALSE)
# npi <- preprocess("xlsx/Encounter.xlsx", 0, c("PATIENT_DISPLAY_ID", "FACILITY_DISPLAY_ID", "CASE_ID"), exclude, 10)
# npi$individual <- paste(npi$PATIENT_DISPLAY_ID, npi$FACILITY_DISPLAY_ID)
# write.table(npi, "csv/encounters/npi.csv", sep="\t", col.names=TRUE, row.names=FALSE)
# medication <- preprocess("xlsx/Encounter.xlsx", 0, c("PATIENT_DISPLAY_ID", "FACILITY_DISPLAY_ID", "CASE_ID"), exclude, 11)
# medication$individual <- paste(medication$PATIENT_DISPLAY_ID, medication$FACILITY_DISPLAY_ID)
# write.table(medication, "csv/encounters/medication.csv", sep="\t", col.names=TRUE, row.names=FALSE)
# trial <- preprocess("xlsx/Encounter.xlsx", 0, c("PATIENT_DISPLAY_ID", "FACILITY_DISPLAY_ID", "CASE_ID"), exclude, 12)
# trial$individual <- paste(trial$PATIENT_DISPLAY_ID, trial$FACILITY_DISPLAY_ID)
# write.table(trial, "csv/encounters/trial.csv", sep="\t", col.names=TRUE, row.names=FALSE)
# scoliosis <- preprocess("xlsx/Encounter.xlsx", 0, c("PATIENT_DISPLAY_ID", "FACILITY_DISPLAY_ID", "CASE_ID"), exclude, 13)
# scoliosis$individual <- paste(scoliosis$PATIENT_DISPLAY_ID, scoliosis$FACILITY_DISPLAY_ID)
# write.table(scoliosis, "csv/encounters/scoliosis.csv", sep="\t", col.names=TRUE, row.names=FALSE)
# tracheostomy <- preprocess("xlsx/Encounter.xlsx", 0, c("PATIENT_DISPLAY_ID", "FACILITY_DISPLAY_ID", "CASE_ID"), exclude, 14)
# tracheostomy$individual <- paste(tracheostomy$PATIENT_DISPLAY_ID, tracheostomy$FACILITY_DISPLAY_ID)
# write.table(tracheostomy, "csv/encounters/tracheostomy.csv", sep="\t", col.names=TRUE, row.names=FALSE)

diagnosis$Genetic.mutation.frame.type <- gsub("Inframe", "In frame", diagnosis$Genetic.mutation.frame.type)
diagnosis$Genetic.mutation.type <- tolower(diagnosis$Genetic.mutation.type)
mutation_types <- data.frame(diagnosis$key, diagnosis$Disease.Type, diagnosis$Genetic.mutation.frame.type, diagnosis$Genetic.mutation.type)
colnames(mutation_types) <- c("key", "Disease.Type", "Genetic.mutation.frame.type", "Genetic.mutation.type")
write.csv(mutation_types, "csv/mutation_types.csv", row.names = FALSE)
